import { fileURLToPath } from "node:url";

import { defineConfig } from "vite-plus";
import packageJson from "./package.json" with { type: "json" };
import BalancedSequencer from "./scripts/ci/test-sequencer.js";

function fromRoot(relativePath: string): string {
  return fileURLToPath(new URL(relativePath, import.meta.url));
}

function browserBundle(entry: string, outDir: string, fileName: string, name: string) {
  return {
    define: {
      "process.env.NODE_ENV": JSON.stringify("production"),
    },
    build: {
      outDir,
      emptyOutDir: false,
      target: "es2022" as const,
      minify: false,
      lib: {
        entry: fromRoot(entry),
        name,
        formats: ["iife" as const],
        fileName: () => fileName,
      },
    },
  };
}

const ciShell = (command: string): string => `bash -lc '${command.replaceAll("'", "'\\''")}'`;
// Cache/dependency metadata stays in CI tasks; the command itself has one owner in package.json.
const ciScript = (name: keyof typeof packageJson.scripts): string =>
  ciShell(packageJson.scripts[name]);

function ciTestShard(shard: number) {
  const report = `.generated/unit-timings-${shard}.json`;
  return {
    command: ciShell(
      `vp exec tsx scripts/ensure-directories.ts .generated && ${packageJson.scripts.test} --reporter=dot --reporter=json --outputFile.json=${report} --shard=${shard}/4`,
    ),
    output: [report],
  };
}

const vendoredAgentSkillPatterns = [".agents/skills/archify/**"];

export default defineConfig(({ mode }) => ({
  publicDir: false,
  resolve: {
    alias: {
      "cloudflare:workers": fromRoot("./test/stubs/cloudflare-workers.ts"),
    },
  },
  lint: {
    ignorePatterns: vendoredAgentSkillPatterns,
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
  },
  fmt: {
    ignorePatterns: vendoredAgentSkillPatterns,
  },
  test: {
    environment: "node",
    reporters: ["dot"],
    include: ["test/**/*.test.ts", "test/**/*.test.tsx"],
    sequence: { sequencer: BalancedSequencer },
  },
  run: {
    tasks: {
      "ci:lint": ciScript("lint"),
      "ci:format-check": ciScript("format:check"),
      "ci:no-js-source": ciScript("check:no-js-source"),
      "ci:types-worker": {
        command: ciScript("types:worker"),
        input: ["wrangler.jsonc", "package.json", "package-lock.json"],
        output: [".generated/worker-configuration.d.ts"],
      },
      "ci:typecheck": {
        // Run only the compiler here: declarations are restored/generated by the dependency.
        command: ciShell("vp exec tsc --noEmit"),
        dependsOn: ["ci:types-worker"],
        output: [],
      },
      "ci:test-shard-1": ciTestShard(1),
      "ci:test-shard-2": ciTestShard(2),
      "ci:test-shard-3": ciTestShard(3),
      "ci:test-shard-4": ciTestShard(4),
      "ci:parser-benchmark": {
        command: ciScript("benchmark:parser"),
        output: [],
      },
      "ci:build-public": ciScript("build:frontend:public"),
      "ci:build-admin": ciScript("build:frontend:admin"),
      "ci:build-worker": {
        command: ciScript("build:worker"),
        dependsOn: ["ci:build-public"],
      },
      "ci:build-admin-worker": {
        command: ciScript("build:admin-worker"),
        dependsOn: ["ci:build-admin"],
      },
      "ci:build-lambda": ciScript("build:lambda"),
      "ci:build": {
        command: "true",
        dependsOn: ["ci:build-worker", "ci:build-admin-worker", "ci:build-lambda"],
        input: [],
        output: [],
      },
    },
  },
  ...(mode === "public"
    ? browserBundle("./frontend/app.tsx", "public", "app.js", "HiFiScoutApp")
    : mode === "admin"
      ? browserBundle(
          "./frontend/admin-console.tsx",
          "admin-public",
          "admin-console.js",
          "HiFiScoutAdmin",
        )
      : mode === "lambda"
        ? {
            build: {
              outDir: "dist/audiounion-lambda",
              emptyOutDir: true,
              target: "node22",
              minify: false,
              ssr: fromRoot("./infra/audiounion-lambda/index.ts"),
              rolldownOptions: {
                external: [/^node:/u],
                output: {
                  entryFileNames: "index.mjs",
                },
              },
            },
            ssr: {
              noExternal: true,
            },
          }
        : {}),
}));
